### ISSUE TITLE
Coop Leaderboards

### ISSUE THREAD

**Issue by theeggroll** [FAForever/server#195]
Coop leaderboards have been down for a long time. Whenever you play a game in coop it just doesn't appear in the leaderboards. Also some missions have the best times recorded involve people using in game bugs to beat the mission significantly faster than should be possible. More details if needed

**Comment by speed2CZ** [comment]
The game should send the data to the server here https://github.com/FAForever/fa/blob/develop/schook/lua/UserSync.lua#L135

and the server should process it here https://github.com/FAForever/server/blob/develop/server/gameconnection.py#L339

One thing that changed since the Zep time was that the coop now support changing difficulty as well, so that is one thing that should get added to the leaderboards as well. That will also require changing the data sent by the game to include it
Difficulty is represented by a number 1-3, 1 for easy, 2 medium, 3 hard

**Comment by Rackover** [comment]
5ee9b868f1d8a4ed790410ed309ab4e8afa4087f
