### ISSUE TITLE
ladder map not working: Dusty Mounds

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/server#207]
http://forums.faforever.com/viewtopic.php?f=3&t=13217

**Comment by Crotalus** [comment]
`info: DISK: AddSearchPath: 'c:\users\...\documents\my games\gas powered games\supreme commander forged alliance\maps\dusty mounds', mounted as '/maps/dusty mounds/'`

Seems like the map exists on the user's computer, my guess is that this is the known ladder bug where you cannot connect to host due to his/her computer being slower. That one is hopefully fixed with #170.

**Comment by Crotalus** [comment]
OTOH, looking at the logs it seems like they managed to connect so maybe a map issue after all then?

**Comment by JaggedAppliance** [comment]
I don't think it's the same tbh, it says Launch Failed in the top left which never happens with the other bug in my experience.
