### ISSUE TITLE
Player rating not updated properly

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#214]
Only 90% sure since it's late and the code is a mess, but:

It looks like, after a game, a player's rating is only updated in the database but NOT in memory. So if he plays a consecutive game, his old mean/deviation are used again to calculate the rating. Only on login, the data are re-read from the database.

**Comment by micheljung** [comment]
The following screenshots show the symptom:

![image](https://cloud.githubusercontent.com/assets/1864183/19136869/26053e9e-8b70-11e6-9138-600b4f4f59ff.png)

![image](https://cloud.githubusercontent.com/assets/1864183/19136886/36cb25d6-8b70-11e6-9d34-749a2c06dff9.png)

Notice how JaggedAppliance's mean/deviation is the same for both games.

**Comment by micheljung** [comment]
Here is the line of code that updates the in-memory value: https://github.com/FAForever/server/blob/2b88e7205e1d315155db92e84946c73c5ccde5cb/server/games/game.py#L372

So it IS updated in memory

**Comment by shalkya** [comment]
Well at least it is well updated to leader board rating.
So we need to find out where it is not well updated.

also it may be link with the rating being the same in game, if you play game in a row => the rating when you connect to faf will always be the same as the rating displayed in game, even if you played several games since your connection, and that your leader score rating has changed.

also may be linked to connection issue. JA and I realized that it happen a lot with the same persons, especially ZLO who has lot of difficulty to connect to player for ladder game. Actually if ZLO search when someone is searching, it will lead to no connection. He needs to search 1st, and then opponent has to search afterwards. (i'm still doubtful that it may be linked to the 2nd rating bug)

**Comment by Crotalus** [comment]
Is `scoreTime` in that reliable here as a time when rating was persisted? Would be interesting to see if the games ended in non-serial manner due to someone still connected to the old game.

**Comment by micheljung** [comment]
scoreTime is set to `NOW()` when scores OR mean/deviation are set.
Non-serial games are indeed a problem... ratings are calculated when a game ends, so if games overlap you get this situation where you started both with the same rating, and your new rating will be whichever game ends last.
But that doesn't seem to be the case in the game above?

**Comment by micheljung** [comment]
Assuming that this has been solved with #229
