### ISSUE TITLE
Server does not handle missing mod icon

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/server#241]
https://github.com/FAForever/client/issues/490

**Comment by duk3luk3** [comment]
Two ways to fix this - add check for NULL (`None`) icon value in DB, or make DB column NON-NULL and convert missing icon in mod_info into empty string when inserting.

Second is imo better, there should be only one value in the db indicating "no icon".

**Comment by micheljung** [comment]
"Empty string" is for _empty strings_
`NULL` is for _no value_

Why would we use empty string for _no value_?

**Comment by duk3luk3** [comment]
You're right. Where does the mod upload happen?

**Comment by duk3luk3** [comment]
So the mod upload apparently happens in the API. It doesn't appear like the API should ever put an empty string into the `icon` column of the `mod_version` table. But the server uses a table called `table_mod`.

**Comment by micheljung** [comment]
Originally, there was `table_mod` and the upload was done through the server protocol. When I built the mod upload into the API, I split the existing table into `mod` and `mod_version` and created a view `table_mod` so we don't have to adjust server code, because its code will eventually be deleted anyway.
