### ISSUE TITLE
Players are matched vs strong opponents in their first ladder games

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/server#266]
http://forums.faforever.com/viewtopic.php?f=2&t=13920
Players should be matched against lower ranked opponents when they first play ladder, atm you will likely play ~1300 rated players in your first game which is very strong for a beginner.

**Comment by micheljung** [comment]
I think our initial values should be mean=600, dev=200.
http://forums.faforever.com/viewtopic.php?f=2&t=13920&p=142590#p142590

**Comment by GrotheFAF** [comment]
or 750, 250

**Comment by duk3luk3** [comment]
Consenus(?) in dev conference was that starting ranking can't be changed because that would screw with trueskill, but it would work to modify the ranking the matchmaker uses to match people.

A proposed function from blodir is here: https://docs.google.com/spreadsheets/d/1syPnQbQGqgSnub-qI5G11EEKb24h1eYw6obW0JdAjzQ/edit#gid=0

I will take a look at seeing if this can be implemented efficiently.

**Comment by GrotheFAF** [comment]
Before implementing this, it might be worth checking if it is really necessary.
Did any of the 'consensy' know (a reference) why this is necessary?
