### ISSUE TITLE
online vault : game doesn't end up + doesn't match the actual game lenght

### ISSUE THREAD

**Issue by shalkya** [FAForever/server#346]
reported once here already : https://github.com/FAForever/client/issues/988
got told to post in server.
it happened once again, in a more important way.
![image](https://user-images.githubusercontent.com/11618427/42424188-1bb91118-8308-11e8-93ef-3b39117817f2.png)
![image](https://user-images.githubusercontent.com/11618427/42424192-295b8d78-8308-11e8-941c-0bbbb6dd0810.png)
there is several game that are still "on going" even if they are well ended. 
also there is game that have 2-3h lenght, while they last 20 min in game time.

I think there is an issue server side.
refaf doesn't solve the issue.
here is the python lobby log : 
[forever.log](https://github.com/FAForever/server/files/2174154/forever.log)

also when i tried to launch the winter duel game, i ended up into the cobalt valley

same issue on downlord client : 
![image](https://user-images.githubusercontent.com/11618427/42447462-3e87bb28-837a-11e8-81cf-f8efc29b73ac.png)
(taken later, so can't display the several "in-game" games

reboot of computer and rooter doesn't change anything 
![image](https://user-images.githubusercontent.com/11618427/42448002-056031ac-837c-11e8-88f3-104e920c53ee.png)

**Comment by Askaholic** [comment]
#263

**Comment by Askaholic** [comment]
I think this issue comes from the fact that the server doesn't know the game time, and instead has to try measuring the real time that elapsed before all players left the game. This info is not necessarily bad, it just needs to be displayed better so people realize it's real time elapsed and not game time. 

There may be some possible improvements on how the server determines that the game has finished, as a single player leaving the lobby open and walking away from their PC will currently cause the server to consider the game as still "on going" even if the sim has ended.

If we want the vault to show game time, this info will need to be added by the replay server @Wesmania, @norraxx. And if we want to keep both real time elapsed and game time we will need to modify the database schema @Brutus5000.

**Comment by shalkya** [comment]
so you mean 1 player stays a bit longer, the other one quit and play another game direct after. And the time he is spending in this game will be added to the time of the previous game ?
This doesn't really match up with what i'm seeing in the screenshot. For example there is game played the day before, and nearly 24h after there is another one played, and this game has time added on top of previous games time.
what's more "likely" is that the player isn't sending "game finish" to the server (but only game started), so the time add up every time he plays another, until for some reason he send a "game finished" message, which stop all the game time counting.

**Comment by Wesmania** [comment]
I don't think the replay server can detect a game ending any better than the client + lobby server can. I assume FA keeps the socket to the replay server open as long as it's running, so it's no better than the client notifying the server that FA quit.

**Comment by Askaholic** [comment]
Hm. I'm not sure what's going on with the 1v1 games. Obviously `SilverChronos` is not staying in the game for 3 hours since he is playing more ladder. So that would mean his opponents are staying in the game. The one where it's `SilverChronos` vs `Chosen` twice in a row, doesn't have the long game issue.

The replay server at least knows the actual game time though right? Because if the game is running at -5, the lobby server has no way of knowing (maybe it could with Bottleneck and BottleneckCleared but this is not implemented), it will just think the game is going longer. But in the replay you will see that right?

**Comment by Wesmania** [comment]
The replay server does not parse replay stream content - there's no way to skip over large chunks of data, we'd have to churn through most of it in python.

**Comment by Askaholic** [comment]
Hm, so there is no easy way to get replay length like looking at timestamps of first command and sim ended. How annoying

**Comment by shalkya** [comment]
> So that would mean his opponents are staying in the game.
They aren't staying in the game 3h after the end. What i think, is that the "game end" message isn't sent (for unknown reason)
> The one where it's SilverChronos vs Chosen twice in a row, doesn't have the long game issue.
they do have long game issues. 1st screenshot were taken while he just played them. If you look to the last screenshot, you can see that these games have the issue.

The hypothesis that it is one guy starting another game, while the other is still in the previous game, doesn't hold/work.

**Comment by Askaholic** [comment]
Ah ok. I see what you mean now. I wonder if ICE has had any affect on this. Does it still happen often? I'm just thinking how we could possibly reproduce this on test.

**Comment by norraxx** [comment]
If you would use my version, it does know all info about stream, and length too, and it wouldn't such problem...

Maybe it'd time to think and finally use replay parser?

**Comment by norraxx** [comment]
`Hm, so there is no easy way to get replay length like looking at timestamps of first command and sim ended. How annoying`

There is the way... ;-)

**Comment by norraxx** [comment]
`The replay server does not parse replay stream content - there's no way to skip over large chunks of data`

No, there is the way to skip

**Comment by norraxx** [comment]
I'll leave it here, if you will want to use it, checkout tests or my github https://github.com/FAForever/faf-scfa-replay-parser

Or any questions to private

**Comment by Wesmania** [comment]
Aren't most messages just a dozen or so bytes in size? I still think it'd be prohibitively expensive to parse the stream, I'd love to see profiling data for that. There's a stress test in my server version, if we slightly adapt that to use real replay data we could add parsing code, run a profiler on it and see the impact.

**Comment by Askaholic** [comment]
That would be great if the replay server extracted actual game time information. At peak traffic you would need to be able to handle replay streams for about 1200 concurrent players. And that is assuming every single person is in game. 

If you need extra performance, maybe this could be of use: https://github.com/MagicStack/uvloop. Or write the replay parser in a faster language like Rust :)

**Comment by norraxx** [comment]
Look at tests or replay parser web. Parser jumps trough useless commands.

**Comment by norraxx** [comment]
Replay parser doesn't read whole file, it jumps inside the file.
Every command has some sort of "header", so parser jumps in header by

**Comment by Wesmania** [comment]
A quick check on one replay I have gives me 1k commands in 8 kilobytes of data, that's 8 bytes per command on average. A typical zipped replay is 200 kilobytes or so with 1:3 compression ratio - that gives us about 75k small chunks to go through in python for every single replay. There's no point talking about all this without profiler data and I intend to run tests, but I bet this parsing alone would take 80% cpu time.

**Comment by norraxx** [comment]
You compute length of the replay when the game is ended. So you'll have to do it just once. And yes, seeking trough byte stream and reading that small amount of data will eat you some CPU. Optimization is almost impossible, because you'll understand, that in that situation you'll have to optimize `seek` command in pure python in `io`.

I've already did that way.

**Comment by Wesmania** [comment]
I'll get back to this discussion after I get some profiling data.

**Comment by Wesmania** [comment]
A tight loop that only skips packets takes around 50% of total CPU time. What would we need to do with the data?

**Comment by norraxx** [comment]
There is no other way to read sequence of data.
As I wrote before, you'll skip all data if you'll put right filter and count only `CommandStates.Advance`.
If you run it once at the end, it won't hurt much.

**Comment by Askaholic** [comment]
I think we could actually solve the game time ending problem pretty easily. When the game ends, presumably when you get the "game over" message, it actually sends a GPGNet message called `GameEnded` that is currently just being ignored on the server. We should be using that instead of `GameState:ended` which signals that the exe terminated.
