### ISSUE TITLE
BaseGame.rate_game not implemented

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/server#38]
`BaseGame` defines `rate_game` as abstract method. Only one of the concrete derivatives actually implements it though (`CustomGame`). If the other derivatives require no behaviour in this method, then perhaps the base class should not specify it as abstract and instead just define it as no-op?

**Comment by Sheeo** [comment]
Indeed `coopGame`, `ladderGame` and `matchmakerGame` have not yet implemented `rate_game()`.

You're likely right that just making it a no-op is better -- since at the moment `BaseGame` is not a real abstract-base-class (ABC), in the sense that is has no virtual subclasses, only actual ones.

I'm leaning towards ditching the entire thing until there's a good reason for introducing an `ABC` for it.

**Comment by Sheeo** [comment]
Then again, it's quite in the infancy of the design process at this point, it was introduced to allow `Game` and `GameConnection` to share things without introducing a cyclic dependency.
