### ISSUE TITLE
Coop leaderboards doesn't validate game settings

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/server#387]
Report from the forums: https://forums.faforever.com/viewtopic.php?f=3&t=17070

The server should check if the game was played without any sim mods and with defaults settings. Else the replay should not be added into the leaderboards.

**Comment by Askaholic** [comment]
Can you try to list out all of the criteria that need to be met for a coop game to be eligible for the leaderboard?

* No sim mods
* Hard Difficulty
* Sandbox mode

what else?

**Comment by speed2CZ** [comment]
No sim mods

game settings:
(key - value)
```
Victory - 'sandbox'
TeamSpawn - 'fixed'
CivilianAlliance - 'enemy'
NoRushOption - 'Off'
PrebuiltUnits - 'Off'
FogOfWar - 'explored'
TeamLock - 'locked'
RevealCivilians - 'No'
GameSpeed - 'normal'
CheatsEnabled - 'false'
AIReplacement - 'Off'
Difficulty - 3
Expansion - true
```

is there a list of settings for a normal game to be ranked, so I can compare it if I didnt forget anything...

**Comment by Askaholic** [comment]
Here's a link to the code which currently does the validity checks. I am going to rework this so that there are some checks which always happen (like cheats) and some checks which happen for different game modes (coop, faf, ladder1v1)

[https://github.com/FAForever/server/blob/97933f6b17567e531303c32994b895ce80ec673d/server/games/game.py#L539](https://github.com/FAForever/server/blob/97933f6b17567e531303c32994b895ce80ec673d/server/games/game.py#L539)
