### ISSUE TITLE
Implement a way for the party leader to determine whether party members are still in-game

### ISSUE THREAD

**Issue by cleborys** [FAForever/server#703]
I just had @BlackYps fill me in on the current state of TMM and he brought this up as an open issue but we didn't find a ticket:

It seems that when a player exits a game (or maybe just a TMM game) early, they cannot queue up for TMM again before the game has finished since the party leader will believe they are in an active game. That seems to be because the party leader checks the player lists of active games in `game_info` to determine whether a party member is still in-game, but this list shows all players present at game start and not players currently in the game.

As far as I'm aware there is currently no way for the server to know that a player has left a game before it ended. BlackYps opened https://github.com/FAForever/downlords-faf-client/issues/2125 for a message to be sent by the client in that case.
To resolve this it seems likely that either the player lists in `game_info` need to be updated on such messages or a player in-game status that is broadcasted should be added.

**Comment by BlackYps** [comment]
To be more precise the client checks the players' status that is set every time a message from the server comes in with the list of active games. Because of this is it probably easier (from the client's point of view) to have the player be removed from that list the server sends, because then we don't have to touch the client's logic that determines if a player is in a game.

**Comment by Askaholic** [comment]
This is another issue with the `Game` code being a complete mess. The `Game.players` property is pretty complicated:
https://github.com/FAForever/server/blob/2cd034c6f194e11ada8257cec488469b3633ee43/server/games/game.py#L167-L190
https://github.com/FAForever/server/blob/2cd034c6f194e11ada8257cec488469b3633ee43/server/games/game.py#L674-L683

It freezes the player list when the game is launched, because it needs to know who's game_player_stats records to update when the game finishes. It used to need this because game_player_stats contained the rating changes, but with the new leaderboard tables, maybe we can refactor to have the gps entries updated as soon as someone disconnects? Still kindof sketchy, because what if they haven't died, and they manage to reconnect later?

Still, I think we need to simplify the `players` property to just show currently connected players, and manage the player freezing through a separate attribute.
