### ISSUE TITLE
Support generated maps in map pools

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#725]
It would be nice if we were able to incorporate generated maps into map pools. We would want to be able to define a probability of getting a generated map as well as specifying at least some parameters like map size, and maybe number of spawns.

Some details we need to figure out:
1. Do we generate the seed/map name on the server, or let the host's client do it?
    1.1. If we let the client do it, how do we tell it the map size and other parameters we want to be fixed?
2. Data format for adding generated maps to map pools.
3. Do we require a particular version of the map generator when adding generated maps to a map pool?

**EDIT**

1. Generate seed/map name on the server
2. 
    2.1. Add json field with generator parameters. 
    2.2. Add weight field to `map_pool_map_version`.
3. Version fixed in json parameters

**Comment by Sheikah45** [comment]
Just going to add some of my opinions here.

1. I think it would be best to generate the seed/map name on the server as the clients already are able to handle receiving a generated map name in the game_info and game_launch message and using that to generate a map. This would then only require adding the map-name encoding to the server which is the prefix neroxis_map_generator_{version}_{Base32Long}_{Base32EncodedParameters}. This is also the easiest way to control the map size and spawn count.
On the other hand you could potentially define a new command or message that gives the client the parameters of map generation as command line arguments to the generator however this would then require changes to the client as well as adding communication back to the server to get the map name.

2. Not as familiar with this but unless things really change may just need to add in a "special entry key" as much as we love those unless we make the change server side but then I am not sure how much that would be easily changed and configurable

3. Yes please pinning a version would be nice so that I don't have to worry about updates breaking things or changing them in undesirable ways. It ideally could be a part of some easily changed db entry or configuration file so it can be easily updated as desired.

**Comment by Askaholic** [comment]
I'd rather avoid defining a new command, so I think having the server generate the map name will be the way to go. The only reservation I have is that this adds a dependency on knowing the format of the generator string, and any future additions to that would need a server change as well. But I think that's a pretty minor concern, and the simplicity of just sending the map name is a significant advantage.

@Brutus5000 proposed that the data required to define a generated map in a map pool could be added as a json field on the `map_pool_map_version` table with the `map_version_id` set to null. This would give us quite a bit of flexibility in controlling the parameters used. Maybe we want to go one step further though, and add a new table to define generated map parameters so they could be re-used between map pools without duplicating the data.

For instance if we store everything as json we might have something like this (I just made up the parameter names):
```json
{
    "type": "neroxis_map_generator",
    "version": "1.3.3",
    "params": {
        "size": "10km",
        "spawns": 4
    }
}
```

Or if we create another table the equivalent entry might look like:
```
+----+------+---------+-------------------------------+
| id | type | version | params                        | 
+----+------+---------+-------------------------------+
|  1 |    0 | 1.3.3   | {"size": "10km", "spawns": 4} |
+----+------+---------+-------------------------------+
```
Where type would be an enum which could be added to in case anyone writes another map generator, or we find some other need for it.

It seems to me like there might be some pretty common map generator presets that might be used many times (like specific map size and fixed number of spawns) so it would be nice to avoid too much potentially duplicated data.

I also wonder if there would be a reason to allow certain expressions in the json that would be evaluated by the server, for example `"spawns": "$team_size * 2"`. It might be a bit overkill since you could probably just define multiple entries with the specific parameters you want, and link those to the pool separately, but again it could reduce the amount of data stored in the db especially if you want to define certain combinations of parameters.

**Comment by Sheikah45** [comment]
On the note of potentially tying the format of the string to the server one workaround might be if there was a mode of the generator code that just took in the parameters and spat out the appropriate name that would exist on the server but not sure how feasible this is.

**Comment by Askaholic** [comment]
I don't think that would be any better really. Plus then I'd have to add Java to the docker container
