### ISSUE TITLE
Lobby list json additional info.

### ISSUE THREAD

**Issue by Kazbek** [FAForever/server#812]
May be add player id and map version id fields to lobby json?
If player change name he cant be found until re login.
Find map by name may cost a lot for server sometimes.

**Comment by Askaholic** [comment]
To be clear, you're talking about the `game_info` message right? Looks like it has `mapname` and `map_file_path` but no id or version id. @Sheikah45 how does the client find the map preview and stuff right now? Would it be better to use map version id and deprecate the other fields?

https://github.com/FAForever/server/blob/369dc07e234b27bc6216909f4e9802d04b8bc7d4/server/games/game.py#L886-L913

**Comment by Kazbek** [comment]
Yes, this is what Im talking about.
Also available by this link https://www.faforever.com/lobby_api?resource=lobby

**Comment by Brutus5000** [comment]
You can lookup maps by filename in the api, but as Kazbek stated, looking up a version id is cheaper (primary key vs string comparison)

**Comment by Brutus5000** [comment]
The filename has to stay though for not uploaded maps

**Comment by Sheikah45** [comment]
Correct you cannot use just the map I'd because then for example no one could know you play a generated map. Or a map that you have locally.

**Comment by Sheikah45** [comment]
Also realized I never answered the original question. @Askaholic the preview location is derived from the map name so we don't need to query the api in order to load the preview which is preferable. Right now the api is only queried when you launch a game. So it would not be better to use the id for either the map or the player because then that would require querying the api for all of these messages which is a lot of messages. And all the clients doing this would be a very big load on the server.

**Comment by Askaholic** [comment]
I think the player id is fine since that will just be an in memory lookup anyways (player_info message contains the id and name). The rename issue is actually similar to the avatar issue if we were to move those to the api, since there is no way for the server to be notified when data that it assumes to be mostly static is changed by an API call.

**Comment by KaukaHan** [comment]
i can add  player id there. @Kazbek only question is, do you mean the hostplayers id ?

**Comment by Askaholic** [comment]
@Sheikah45 do we need both `mapname` and `map_file_path` or can we get rid of one?

**Comment by Kazbek** [comment]
@KaukaHan Host and all players. Since I need to iterate all of them.

**Comment by Kazbek** [comment]
Probably to backward compatibility will need add it as new field instead of modifying "Teams".

**Comment by KaukaHan** [comment]
yeah Askaholic wont like modifiing existing fields.

**Comment by KaukaHan** [comment]
@Kazbek is the order of ids relevant ?

**Comment by Kazbek** [comment]
No, it doesnt matter

**Comment by Sheikah45** [comment]
@Askaholic I just checked and the client currently only uses mapname

**Comment by Kazbek** [comment]
Remove "map_file_path" without adding mapVersionId imho a bad idea.
I use it in API query and for mapname it was falling out by timeout. Was discussed few months ago in zulip that this field doesnt have index in datqabase.

**Comment by Askaholic** [comment]
I’m just wondering because I think mapname an map_file_path are derived from the same variable internally. If we could replace one with map_version_id and sill maintain support for mapgen and coop then that might be ideal

**Comment by Askaholic** [comment]
@Gatsik anything to add?

**Comment by KaukaHan** [comment]
i dont want to dragg this out with some side quests. May it be possible for me to just add the player-ids and, if needed, the map related fields can be the subject of another issue ?

**Comment by Askaholic** [comment]
Yea that’s fine

**Comment by Askaholic** [comment]
So as @Brutus5000 pointed out on the PR. Maybe we want to redesign the format of the message. The main problem we're running into is we have a list of flat values that currently contain the login names. We can't add any additional info to these list items because they are scalar values.

If we use lists of dictionaries instead then we have more flexibility to add additional attributes in the future if the need arises. The only downside is it makes the message larger and potentially more complicated to parse.

```json
{
    "teams": [
        {
            "team_id": 1,
            "players": [
                {
                    "id": 12345
                }
            ]
        }
    ]
}
```

**Comment by KaukaHan** [comment]
I have implement that sheme Askaholic proposed.
