### ISSUE TITLE
TMM queue pop timer can march to negative infinity

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/server#970]
It looks like there is an issue where the pop timer can get into some kind of loop that marches down to 0 then negative infinity and then can never recover.

Server graph attached
![image](https://github.com/FAForever/server/assets/66929319/873f1c5b-096f-42ef-b4c9-563504e29842)

Not sure from the logs what caused it but occurred around 17:07 US east on July 27th

**Comment by Sheikah45** [comment]
The beginning of the end
<html><body>
<div class="css-as6nqd-verticalScroll"><span class="css-1wx8bl8-positionRelative"><span><span class="">INFO     Jul 27  20:58:41 PopTimer                       Next tmm3v3 wave happening in 61s</span></span></span><span class="log-row-menu css-zaiqsn"></span></div>

  |  
-- | --


<div class="css-as6nqd-verticalScroll"><span class="css-1wx8bl8-positionRelative"><span><span class="">INFO     Jul 27  21:06:18 PopTimer                       Next tmm3v3 wave happening in 7s</span></span></span></div>
</body>
</html>

**Comment by Askaholic** [comment]
Looks like this can happen because the way we compute the 'queue rate' is just the number of players in queue over the time since the last pop. This would only be correct if players re-queue each time they fail to find a match. However, since that's not how the queue works, if a large number of players remains unmatched in the queue for a while, the time can start marching down, and once it gets to a critical level it will start marching down very fast.

**Comment by Askaholic** [comment]
A quick solution would be to add a minimum pop time to prevent that from happening, but the underlying issue is that the 'queue rate' is not calculated correctly.
